---
- name: Set the following firewall rules on add-port=6443/tcp
  shell: firewall-cmd --permanent --add-port=6443/tcp

- name: Set the following firewall rules on add-port=2379-2380/tcp
  shell: firewall-cmd --permanent --add-port=2379-2380/tcp

- name: Set the following firewall rules on add-port=10250/tcp
  shell: firewall-cmd --permanent --add-port=10250/tcp

- name: Set the following firewall rules on add-port=10251/tcp
  shell: firewall-cmd --permanent --add-port=10251/tcp

- name: Set the following firewall rules on add-port=10252/tcp
  shell: firewall-cmd --permanent --add-port=10252/tcp

- name: Set the following firewall rules on add-port=10253/tcp
  shell: firewall-cmd --permanent --add-port=10255/tcp

- name: firewall reload
  service:
    name: firewalld
    state: reloaded

- name: Set the following firewall rules on bridge-nf-call-iptables
  shell: echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables
  
#- name: Initializing the kubernetes cluster on the master node…
  #shell: kubeadm init --pod-network-cidr="{{ CIDR_RANGE }}" >> cluster_initialized.txt
  #args:
    #chdir: $HOME
    #creates: cluster_initialized.txt
- name: Initializing the kubernetes cluster on the master node…
  shell: kubeadm init --pod-network-cidr=10.30.116.0/24
  register: result
  until: result.stdout.find("Your Kubernetes master has initialized successfully!") != -1
  retries: 1
  delay: 20    

- name: Creating .kube directory
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: Configuring users cluster access
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ansible/.kube/config
    remote_src: yes
    owner: root

- name: Installing Pod network…. (Flannel)
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.txt
  args:
    chdir: $HOME
    creates: pod_network_setup.txt
