---
- name: Install Docker
  yum:
    name: docker
    state: present
    update_cache: true

- name: docker start
  service:
    name: docker
    state: started

#- name: disable SElinux
#  shell: setenforce 0

- name: ensure net.bridge.bridge-nf-call-ip6tables is set to 1
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: 1
    state: present

- name: ensure net.bridge.bridge-nf-call-iptables is set to 1
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    state: present

- name: adding kubernetes repository
  file: 
    src: files/kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
    owner: root
    group: root
    mode: '1777'

- name: install kubelet
  yum:
    name: kubelet
    state: present
    update_cache: true

- name: install kubeadm
  yum:
    name: kubeadm
    state: present

- name: start kubelet
  service:
    name: kubelet
    enabled: yes
    state: started

- name: install kubectl
  yum:
    name: kubectl
    state: present
    allow_downgrade: yes    
