- name: Disabling swap on hosts
  shell: swapoff -a

- name: Disabling swap from fstab…
  replace:
    path: /etc/fstab
    regexp: ‘^([^#].*?\sswap\s+sw\s+.*)$’
    replace: ‘# \1’

- name: Creating kubernetes config file for host network…
  file:
    src: files/k8s.conf
    dest: /etc/sysctl.d/k8s.conf
    owner: root
    group: root
    mode: '1777'
    
- name: Applying sysctl file config…
  shell: sysctl --system

- name: Applying newly created kubernetes config file…
  shell: sysctl -p /etc/sysctl.d/k8s.conf

- name: Deploying docker iptables rule…
  shell: iptables -P FORWARD ACCEPT

- name: Disabling UFW…
  ufw:
    state: disabled
